name: ricer
version: '${project.version}'
main: com.caltr.ricer.Ricer
api-version: '1.20'
depend: [ProtocolLib]
permissions:
  ricer.items:
    description: Allows the user to run the item command.
    default: op
commands:
  item:
    description: lifter - gives you custom items in Ricer
    usage: /item <item>
    permission: ricer.items
    permission-message: You don't have sufficient permissions to run this command!
