name: ricer
version: '5.7'
main: com.caltr.ricer.Ricer
api-version: '1.20'
depend: [ProtocolLib]
permissions:
  ricer.items:
    description: Allows the user to run the lifterCommand command.
    default: op
commands:
  lifter:
    description: lifter - gives you the Lifter item
    usage: /lifter
    permission: ricer.items
    permission-message: You don't have sufficient permissions to run this command!

  zeushelmet:
    description: zeushelmet - gives you the Enlightenment helmet
    usage: /zeushelmet
    permission: ricer.items
    permission-message: You don't have sufficient permissions to run this command!

  luigilight:
    description: luigilight - gives you the Luigi Flashlight item
    usage: /luigilight
    permission: ricer.items
    permission-message: You don't have sufficient permissions to run this command!

  tod:
    description: tod
    usage: /tod
    permission: ricer.items
    permission-message: You don't have sufficient permissions to run this command!
  punch:
    description: punch
    usage: /punch
    permission: ricer.items
    permission-message: You don't have sufficient permissions to run this command!
  punchcombo:
    description: punchcombo
    usage: /punchcombo
    permission: ricer.items
    permission-message: You don't have sufficient permissions to run this command!
